import { createContext, useContext, useState, type ReactNode } from 'react'

export type Language = 'en' | 'tr'
type Dictionary = Record<string, string>

const english: Dictionary = {
  features: 'Features', privacy: 'Privacy', github: 'GitHub', website: 'Website', local: '100% local', aiLegalNote: 'AI mode uses the open-source AGPL background removal engine and never uploads your image.', workspaceFooter: 'One workspace for every image.', supportedFormats: 'Supported formats',
  eyebrow: 'A quieter image workflow', heroTitle: 'Free image tools.', heroTitleAccent: 'No uploads.', heroDescription: 'Compress, resize, convert and edit your images directly in your browser. Fast, private, and yours alone.', chooseImage: 'Choose image', tryDemo: 'Try a demo', visitWebsite: 'Visit padrosum.uk', trust: 'Your images never leave your device.', freeForever: 'Free forever',
  dropImages: 'Drop your images here', chooseFromDevice: 'or choose from your device', chooseImages: 'Choose images', supportedUpload: 'PNG · JPG · WebP · AVIF',
  projects: 'Projects', untitled: 'Untitled project', savedLocally: 'Saved locally', newProject: 'New project', tools: 'Tools', privateByDesign: 'Private by design', nothingLeaves: 'Nothing leaves this device.',
  optimize: 'Optimize', edit: 'Edit', ai: 'AI', export: 'Export', compress: 'Compress', resize: 'Resize', convert: 'Convert', crop: 'Crop', rotate: 'Rotate & flip', adjust: 'Adjust', removeBackground: 'Remove background',
  compressIntro: 'Reduce file size while keeping your image looking sharp.', smartOptimize: 'Smart Optimize', smartOptimizeHint: 'Choose format, size and quality automatically.', outputFormat: 'Output format', quality: 'Quality', originalSize: 'Original size', optimizedSize: 'Optimized size',
  resizeIntro: 'Set exact dimensions or scale your image proportionally.', cropIntro: 'Frame the part of your image you want to keep.', rotateIntro: 'Rotate your image or mirror it along an axis.', adjustIntro: 'Fine-tune the image without changing the original file.',
  backgroundIntro: 'Remove backgrounds locally. Your image stays on this device during processing.', fastCutout: 'Fast cutout', aiModel: 'AI model', runsOnDevice: 'Runs on this device', noModelDownload: 'No model download required.', runAi: 'Run local AI removal', aiRemovalOn: 'AI removal on', backgroundRemovalOn: 'Background removal on',
  processingLocally: 'Processing locally...', modelReady: 'Model result ready', exportImage: 'Export image', processing: 'Processing...', downloadZip: 'Download all as ZIP',
  original: 'Original', preview: 'Preview', backWorkspace: 'Back to workspace', openPixora: 'Open Pixora', featuresPageTitle: 'A sharper workflow.', featuresPageAccent: 'Nothing extra.', privacyPageTitle: 'Your images stay', privacyPageAccent: 'with you.', balanced: 'Balanced', smallerFile: 'Smaller file', higherQuality: 'Higher quality',
  featuresLead: 'A focused set of image tools built to run locally, stay fast, and get out of your way.', privacyLead: 'Pixora is built around a simple promise: image processing should not require handing your files to a server.', privacyShort: 'The short version', privacyShortTitle: 'There is no upload step.', privacyShortText: 'When you choose an image, your browser reads it through the File API and creates a local object URL. Processing happens in canvas, Web Workers, WASM or WebGPU on your device.', whatPixoraDoes: 'What Pixora does', whatPixoraDoesNot: 'What Pixora does not do', aiPrivacyNote: 'AI background removal downloads model and runtime files from its configured asset host on first use. Your image is passed to the local browser engine, not to that host.',
  privacyDoes1: 'Reads files you explicitly choose, paste or drop.', privacyDoes2: 'Creates temporary local object URLs for previews.', privacyDoes3: 'Stores model assets in the browser cache when AI mode is used.', privacyDoes4: 'Revokes temporary URLs when a project is reset or closed.', privacyNot1: 'Uploads images to a Pixora backend.', privacyNot2: 'Creates accounts, profiles or image histories.', privacyNot3: 'Uses analytics, tracking pixels or advertising identifiers.', privacyNot4: 'Sends image pixels to the AI model provider.',
  featureOptimize: 'Optimize locally', featureOptimizeText: 'Resize, compress and convert PNG, JPEG, WebP and AVIF files without an upload.', featureEdit: 'Edit with control', featureEditText: 'Crop, rotate, flip and adjust images through a non-destructive transformation state.', featureBatch: 'Batch without a backend', featureBatchText: 'Apply the same settings across a queue, process files in workers and download one ZIP.', featureAi: 'AI on your device', featureAiText: 'Background removal uses a local WebGPU/WASM model. The first model and runtime download is about 75 MB and is cached locally.', featureOffline: 'Works offline', featureOfflineText: 'The static PWA caches its shell so the core editor can keep working without a network connection.', featureFree: 'Free Software', featureFreeText: 'Pixora is released under GPL-3.0 with third-party license notices included in the repository.',
  language: 'Language', english: 'English', turkish: 'Türkçe', freeSoftwareNotice: 'Pixora is Free Software.', width: 'Width', height: 'Height', aspectRatio: 'Aspect ratio', scale: 'Scale', flip: 'Flip', horizontal: 'Horizontal', vertical: 'Vertical', resetCrop: 'Reset crop', brightness: 'Brightness', contrast: 'Contrast', saturation: 'Saturation', exposure: 'Exposure', blur: 'Blur', sharpen: 'Sharpen', filename: 'Filename', queued: 'Queued', ready: 'Ready', failed: 'Failed', cancelled: 'Cancelled', cancel: 'Cancel', metadataCleaned: 'Metadata removed', metadataDescription: 'EXIF and GPS data are removed locally on export.',
}

const turkish: Dictionary = {
  features: 'Özellikler', privacy: 'Gizlilik', github: 'GitHub', website: 'Website', local: '%100 yerel', aiLegalNote: 'Yapay zekâ modu, açık kaynaklı AGPL arka plan kaldırma motorunu kullanır ve görselini hiçbir yere yüklemez.', workspaceFooter: 'Her görsel için tek bir çalışma alanı.', supportedFormats: 'Desteklenen formatlar',
  eyebrow: 'Daha sakin bir görsel çalışma alanı', heroTitle: 'Ücretsiz görsel araçları.', heroTitleAccent: 'Yükleme yok.', heroDescription: 'Görsellerini doğrudan tarayıcında sıkıştır, yeniden boyutlandır, dönüştür ve düzenle. Hızlı, özel ve tamamen senin kontrolünde.', chooseImage: 'Görsel seç', tryDemo: 'Demoyu dene', visitWebsite: 'padrosum.uk sitesini ziyaret et', trust: 'Görsellerin cihazından ayrılmaz.', freeForever: 'Her zaman ücretsiz',
  dropImages: 'Görsellerini buraya bırak', chooseFromDevice: 'veya cihazından seç', chooseImages: 'Görsel seç', supportedUpload: 'PNG · JPG · WebP · AVIF',
  projects: 'Projeler', untitled: 'İsimsiz proje', savedLocally: 'Yerelde kaydedildi', newProject: 'Yeni proje', tools: 'Araçlar', privateByDesign: 'Gizlilik odaklı', nothingLeaves: 'Hiçbir şey cihazından ayrılmaz.',
  optimize: 'Optimize et', edit: 'Düzenle', ai: 'Yapay zekâ', export: 'Dışa aktar', compress: 'Sıkıştır', resize: 'Yeniden boyutlandır', convert: 'Dönüştür', crop: 'Kırp', rotate: 'Döndür ve çevir', adjust: 'Ayarla', removeBackground: 'Arka planı kaldır',
  compressIntro: 'Görsel kalitesini mümkün olduğunca koruyarak dosya boyutunu küçült.', smartOptimize: 'Akıllı optimize et', smartOptimizeHint: 'Formatı, boyutu ve kaliteyi otomatik olarak seç.', outputFormat: 'Çıktı formatı', quality: 'Kalite', originalSize: 'Orijinal boyut', optimizedSize: 'Optimize edilmiş boyut',
  resizeIntro: 'Kesin ölçüler belirle veya görseli orantısını koruyarak ölçekle.', cropIntro: 'Görselinde kalmasını istediğin alanı seç.', rotateIntro: 'Görselini döndür veya yatay/dikey eksende çevir.', adjustIntro: 'Orijinal dosyaya dokunmadan görselin görünümünü ayarla.',
  backgroundIntro: 'Arka planı yerel olarak kaldır. Görselin işlem boyunca bu cihazda kalır.', fastCutout: 'Hızlı arka plan kaldırma', aiModel: 'Yapay zekâ modeli', runsOnDevice: 'Bu cihazda çalışır', noModelDownload: 'Model indirmeye gerek yok.', runAi: 'Yapay zekâ ile kaldır', aiRemovalOn: 'Yapay zekâ ile kaldırma açık', backgroundRemovalOn: 'Arka plan kaldırma açık',
  processingLocally: 'Yerel olarak işleniyor...', modelReady: 'Model sonucu hazır', exportImage: 'Görseli dışa aktar', processing: 'İşleniyor...', downloadZip: 'Tümünü ZIP indir',
  original: 'Orijinal', preview: 'Ön izleme', backWorkspace: 'Çalışma alanına dön', openPixora: 'Pixora\'yı aç', featuresPageTitle: 'Daha akıcı bir çalışma.', featuresPageAccent: 'Gereksiz hiçbir şey yok.', privacyPageTitle: 'Görsellerin', privacyPageAccent: 'seninle kalır.', balanced: 'Dengeli', smallerFile: 'Daha küçük dosya', higherQuality: 'Daha yüksek kalite',
  featuresLead: 'Hızlı çalışan, yerel işleme odaklı ve işin bittiğinde kenara çekilen sade bir görsel araç seti.', privacyLead: 'Pixora tek bir ilke üzerine kurulu: görsellerini işlemek için dosyalarını bir sunucuya teslim etmek zorunda kalmamalısın.', privacyShort: 'Kısaca', privacyShortTitle: 'Ortada bir yükleme adımı yok.', privacyShortText: 'Bir görsel seçtiğinde tarayıcın dosyayı File API ile okur ve yerel bir object URL oluşturur. Tüm işlemler cihazındaki canvas, Web Worker, WASM veya WebGPU üzerinde gerçekleşir.', whatPixoraDoes: 'Pixora ne yapar?', whatPixoraDoesNot: 'Pixora ne yapmaz?', aiPrivacyNote: 'Yapay zekâ ile arka plan kaldırma, ilk kullanımda model ve çalışma zamanı dosyalarını ayarlı kaynaktan indirir. Görselin bu kaynağa gönderilmez; cihazındaki yerel motora aktarılır.',
  privacyDoes1: 'Yalnızca seçtiğin, yapıştırdığın veya sürükleyip bıraktığın dosyaları okur.', privacyDoes2: 'Ön izleme için geçici yerel object URL’ler oluşturur.', privacyDoes3: 'Yapay zekâ kullanıldığında model dosyalarını tarayıcı önbelleğinde saklar.', privacyDoes4: 'Proje sıfırlandığında veya sayfa kapandığında geçici URL’leri temizler.', privacyNot1: 'Görselleri bir Pixora sunucusuna yüklemez.', privacyNot2: 'Hesap, profil veya görsel geçmişi oluşturmaz.', privacyNot3: 'Analitik, takip kodu veya reklam tanımlayıcısı kullanmaz.', privacyNot4: 'Görsel piksellerini yapay zekâ model sağlayıcısına göndermez.',
  featureOptimize: 'Yerelde optimize et', featureOptimizeText: 'PNG, JPEG, WebP ve AVIF görsellerini yüklemeden yeniden boyutlandır, sıkıştır ve dönüştür.', featureEdit: 'Kontrollü düzenle', featureEditText: 'Görseli değiştirmeden kırp, döndür, çevir ve temel ayarlarını düzenle.', featureBatch: 'Sunucusuz toplu işlem', featureBatchText: 'Aynı ayarları bir kuyruğa uygula, dosyaları worker üzerinde işle ve tek bir ZIP olarak indir.', featureAi: 'Cihazında yapay zekâ', featureAiText: 'Arka plan kaldırma, yerel WebGPU/WASM modeli kullanır. İlk model ve çalışma zamanı indirmesi yaklaşık 75 MB’tır; ardından yerelde önbelleğe alınır.', featureOffline: 'Çevrimdışı çalışır', featureOfflineText: 'Statik PWA kabuğu önbelleğe alır; temel düzenleyici internet bağlantısı olmadan da çalışmaya devam eder.', featureFree: 'Özgür Yazılım', featureFreeText: 'Pixora, üçüncü taraf lisans bildirimleriyle birlikte GPL-3.0 altında yayımlanır.',
  language: 'Dil', english: 'English', turkish: 'Türkçe', freeSoftwareNotice: 'Pixora özgür bir yazılımdır.', width: 'Genişlik', height: 'Yükseklik', aspectRatio: 'En-boy oranı', scale: 'Ölçek', flip: 'Çevir', horizontal: 'Yatay', vertical: 'Dikey', resetCrop: 'Kırpmayı sıfırla', brightness: 'Parlaklık', contrast: 'Kontrast', saturation: 'Doygunluk', exposure: 'Pozlama', blur: 'Bulanıklık', sharpen: 'Keskinlik', filename: 'Dosya adı', queued: 'Bekliyor', ready: 'Hazır', failed: 'Başarısız', cancelled: 'İptal edildi', cancel: 'İptal', metadataCleaned: 'Metadata temizlendi', metadataDescription: 'EXIF ve GPS bilgileri dışa aktarım sırasında cihazında kaldırılır.',
}

type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('pixora-language')
    return stored === 'tr' ? 'tr' : 'en'
  })
  const setLanguage = (next: Language) => {
    setLanguageState(next)
    localStorage.setItem('pixora-language', next)
  }
  const dictionary = language === 'tr' ? turkish : english
  return <I18nContext.Provider value={{ language, setLanguage, t: (key) => dictionary[key] ?? english[key] ?? key }}>{children}</I18nContext.Provider>
}

// The hook intentionally lives beside the provider so components share one context.
// eslint-disable-next-line react-refresh/only-export-components
export function useI18n(): I18nValue {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside LanguageProvider')
  return value
}
